### ISSUE TITLE
Incompatibility with PHP 8.0

### ISSUE THREAD

**Issue by MacFJA** [tacoberu/bnf-php#1]
The library is incompatible with PHP 8 due to its use of `Match` as a class name.
Since PHP 8.0.0, `match` is a reserved keyword
https://www.php.net/manual/en/migration80.incompatible.php

---

Either the `Match` class need to be renamed, or the composer.json need to be updated to indicate that the lib is not compatible with PHP 8
```json
	"require": {
		"php" : ">=5.3.3 <8.0.0"
	},
 ```

**Comment by tacoberu** [comment]
OK?
https://github.com/tacoberu/bnf-php/actions/runs/4863942085

**Comment by tacoberu** [comment]
Thanks.
Fixed in v1.2

**Comment by tacoberu** [comment]
fixed
